#!C:\Users\cdydo\OneDrive\바탕 화면\Mines\DGIST\BlackWind\BlackWind_2024_Lightning_VFX_PDE_solver_test\myenv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
